language: node_js
node_js:
  - "node"
before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
notifications:
  email: false
install:
  - DEBUG=true npm install
script:
  - npm run lint
  - npm run test
  - npm run build