name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install, lint, test, build
        run: |
          DEBUG=true npm install
          npm run lint
          npm run test
          npm run build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
